language: ruby
rvm:
        - 2.4.0
notifications:
        email: false
script: bundle exec rails test -b
addons:
        postgresql: "9.6"
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: 
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.6
        - cd test/dummy
        - psql -c 'CREATE DATABASE heb412gen_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.copia
        - sed -e "s/provider = libc,//g" db/structure.sql.copia >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sip:indices
        - cd ../..

