language: ruby
  
rvm:
        - 2.6.1

addons:
        postgresql: "9.6"

notifications:
        email: false

env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
                - CC_TEST_REPORTER_ID=25b2e6c40bbd457e1569bff1c83e9a461986bdfa180cf6049090dd6ac358bdd2

before_install: 
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.6
        - cd test/dummy
        - psql -c 'CREATE DATABASE heb412gen_pru;' -U postgres
        - gem install bundler
        - gem update --system
        - bundle update --bundler
        - bundle install
        - cp db/structure.sql db/structure.sql.copia
        - sed -e "s/provider = libc,//g" db/structure.sql.copia >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sip:indices
        - cd ../..

script: 
        - bundle exec rails test -b

after_script: 
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
